---

- hosts: all 
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: install apache2 package
    apt:
      name: 
        - apache2
      state: latest
    when: ansible_facts['nodename'] == "webserver"

  - name: install tmux
    apt:
      name:
        - tmux
      state: latest
    when: ansible_facts['nodename'] == "webserver" 
