---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: install updates for all
    tags: always
    apt:
      upgrade: dist
      update_cache: yes

#Play 1:
- hosts: db_servers 
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: install apache2 package
    tags: web_server,apache
    apt:
      name: 
        - apache2
      state: latest

  - name: install php package
    tags: web
    apt:
      name:
        - libapache2-mod-php
      state: latest

#Play 2:
- hosts: db_servers
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: install mariadb package
    tags: db, mariadb
    apt:
      name:
        - mariadb-server
      state: latest

#Play 3:
- hosts: file_servers
  become: true
  vars:
    ansible_python_interpreter: auto_silent

  tasks:
  - name: install samba package
    apt:
      name:
        - samba
      state: latest
