---

#Play 1 --> only for web_servers
- hosts: web_servers
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: Remove libapache2, apache2 packages
    apt:
      name:
        - libapache2-mod-php
        - apache2
      state: absent

#play 2 --> only for DataBase Servers
- hosts: db_servers
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:

  - name: Remove mariadb package
    apt:
      name:
        - mariadb-server
      state: absent
